"""Regenerate Piku's firmware bitmaps, expression sheet, and CAD face data.

Run from anywhere: python tools/generate_faces.py
Requires Pillow 10.1 or newer. The OLED artwork itself uses only binary pixels.
"""
import argparse
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

NAMES = ["IDLE", "LOOK_LEFT", "LOOK_RIGHT", "BLINK", "HAPPY", "LOVE", "SLEEP", "SURPRISED", "SHY"]
LABELS = ["Hello", "Curious left", "Curious right", "Blink", "Happy", "Love", "Sleepy", "Surprised", "Shy wink"]


def draw_face(name):
    im = Image.new("1", (128, 64), 0)
    d = ImageDraw.Draw(im)
    d.rounded_rectangle((6, 3, 121, 60), radius=24, outline=1, width=2)
    d.line([(57, 5), (61, 9), (65, 5), (68, 8)], fill=1, width=1)
    for side in (0, 1):
        for j in range(3):
            x = (21 if side == 0 else 99) + j * 4
            d.line((x, 38, x + 1, 41), fill=1, width=1)

    # Directions refer to the viewer's left/right. Eye outlines stay fixed;
    # only the pupils move. Hello and other open eyes look straight ahead.
    pupil_dx = -5 if name == "LOOK_LEFT" else 5 if name == "LOOK_RIGHT" else 0
    for i, x in enumerate((33, 81)):
        if name in ("BLINK", "SLEEP") or (name == "SHY" and i == 1):
            d.arc((x - 2, 19, x + 17, 31), 0, 180, fill=1, width=2)
        elif name == "HAPPY":
            d.arc((x - 2, 18, x + 17, 35), 180, 360, fill=1, width=2)
        elif name == "LOVE":
            d.ellipse((x - 2, 18, x + 8, 28), fill=1)
            d.ellipse((x + 6, 18, x + 16, 28), fill=1)
            d.polygon([(x - 2, 25), (x + 16, 25), (x + 7, 36)], fill=1)
        else:
            top, bottom = (14, 37) if name == "SURPRISED" else (16, 35)
            d.rounded_rectangle((x - 3, top, x + 17, bottom), radius=8, fill=1)
            d.rounded_rectangle((x + 3 + pupil_dx, 21, x + 11 + pupil_dx, 30), radius=3, fill=0)

    if name in ("HAPPY", "LOVE"):
        d.rounded_rectangle((54, 37, 74, 51), radius=7, outline=1, width=2)
        d.line((55, 38, 73, 38), fill=1, width=2)
        d.rectangle((60, 39, 63, 43), fill=1)
        d.rectangle((65, 39, 68, 43), fill=1)
    elif name == "SLEEP":
        d.ellipse((61, 40, 67, 47), outline=1, width=1)
        d.line([(100, 15), (106, 15), (100, 21), (106, 21)], fill=1, width=1)
    elif name == "SURPRISED":
        d.ellipse((58, 40, 70, 53), outline=1, width=2)
    else:
        d.polygon([(61, 34), (67, 34), (64, 37)], fill=1)
        d.line((64, 37, 64, 40), fill=1, width=1)
        d.arc((54, 35, 64, 45), 0, 180, fill=1, width=1)
        d.arc((64, 35, 74, 45), 0, 180, fill=1, width=1)
    if name == "SHY":
        d.ellipse((17, 35, 30, 44), outline=1, width=1)
        d.ellipse((97, 35, 110, 44), outline=1, width=1)
    return im


def pack_frame(im):
    return [sum((1 << (7 - k)) if im.getpixel((x + k, y)) else 0 for k in range(8))
            for y in range(64) for x in range(0, 128, 8)]


def sheet_font(size):
    for name in ("segoeui.ttf", "DejaVuSans.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            pass
    return ImageFont.load_default(size=size)


def generate(root):
    frames = [draw_face(name) for name in NAMES]
    header = ["// Generated by tools/generate_faces.py. 128x64, row-major MSB-first.",
              "// Fixed eye outlines; pupils look centre, viewer-left, or viewer-right.",
              "#pragma once", "#include <Arduino.h>",
              "enum PikuExpression { " + ", ".join("PIKU_" + name for name in NAMES) + " };",
              "static const uint8_t PIKU_FACES[9][1024] PROGMEM = {"]
    for name, im in zip(NAMES, frames):
        data = pack_frame(im)
        assert len(data) == 1024
        header.append("  { // " + name)
        header.extend("    " + ",".join(f"0x{x:02x}" for x in data[i:i + 16]) + ","
                      for i in range(0, 1024, 16))
        header.append("  },")
    header.append("};")
    firmware = root / "firmware" / "Piku"
    firmware.mkdir(parents=True, exist_ok=True)
    (firmware / "piku_faces.h").write_text("\n".join(header) + "\n", encoding="utf-8")

    sheet = Image.new("RGB", (1320, 900), "#fbf8f2")
    d = ImageDraw.Draw(sheet)
    font, small = sheet_font(23), sheet_font(20)
    d.text((38, 24), "Piku  /  the whole face lives on the OLED", fill="#222222", font=font)
    for i, (im, label) in enumerate(zip(frames, LABELS)):
        x, y = 36 + (i % 3) * 432, 86 + (i // 3) * 255
        rgb = Image.new("RGB", im.size, "#101719")
        rgb.paste("#89daf7", mask=im.convert("L"))
        sheet.paste(rgb.resize((384, 192), Image.Resampling.NEAREST), (x, y))
        d.text((x, y + 204), label, fill="#333333", font=small)
    d.text((38, 863), "Exact 128 x 64 artwork  •  One OLED colour  •  Same parts and wiring",
           fill="#666666", font=small)
    sheet.save(root / "Piku-face-expressions.png")
    cad = root / "cad"
    cad.mkdir(parents=True, exist_ok=True)
    pixels = [[int(frames[0].getpixel((x, y))) for x in range(128)] for y in range(64)]
    (cad / "piku_face_pixels.json").write_text(json.dumps(pixels), encoding="utf-8")
    print("Generated nine OLED frames, their preview sheet, and the matching CAD face pixels.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=Path(__file__).resolve().parents[1])
    generate(parser.parse_args().output_root)
